export const SET_ISLOADING = 'SET_ISLOADING';
export const SET_SUBMITTING = 'SET_SUBMITTING';
export const USER_RECEIVED = 'USER_RECEIVED';
export const SINGLE_USER_RECEIVED = 'SINGLE_USER_RECEIVED';
export const USER_ADDED = 'USER_ADDED';
export const USER_REMOVED = 'USER_REMOVED';
export const USER_UPDATED = 'USER_UPDATED';